use mlua::{ExternalResult, Lua};

/// Initializes the connection between `nvim-oximlua` and
/// [`mlua::Lua`].
/// This must be called exactly once at the [mlua module entry point].
///
/// [`mlua::Lua`]: ::mlua::Lua
/// [mlua module entry point]: https://github.com/mlua-rs/mlua#module-mode
///
/// # Examples
///
/// ```ignore
/// use nvim_oximlua as nvim;
/// use mlua::prelude::*;
///
/// #[mlua::lua_module]
/// fn plugin_entry_point(lua: &Lua) -> LuaResult<LuaTable> {
///     nvim::init(lua);
///     let plugin_entry_point = lua.create_table()?;
///     
///     ...
///
///     Ok(plugin_entry_point)
/// }
/// ```
pub fn init(lua: &Lua) -> mlua::Result<()> {
    types::arena_init();

    olua::init(lua).into_lua_err()?;

    #[cfg(feature = "libuv")]
    unsafe {
        lua.exec_raw::<()>((), |state| {
            libuv::init(state);
        })?;
    }

    Ok(())
}

// use core::ffi::c_int;
//
// use luajit::{Pushable, ffi::State};
//
// /// The entrypoint of the plugin.
// ///
// /// Initializes the Lua state, executes the entrypoint function and pushes the
// /// result on the stack.
// #[inline(always)]
// pub unsafe fn entrypoint<T>(lua_state: *mut State, body: fn() -> T) -> c_int
// where
//     T: Pushable,
// {
//     unsafe {
//         types::arena_init();
//
//         luajit::init(lua_state);
//
//         #[cfg(feature = "libuv")]
//         libuv::init(lua_state);
//
//         match body().push(lua_state) {
//             Ok(num_pushed) => num_pushed,
//             Err(lua_err) => luajit::utils::push_error(&lua_err, lua_state),
//         }
//     }
// }

#[cfg(false)] // TODO: Adjust to nvim-oximlua
/// == ORIG DOCS =======================================
///
/// Marks a function as the entrypoint of the plugin.
///
/// The function wrapped by this macro will be called by Neovim when the user
/// loads the plugin by passing its name to the `require` function. It can
/// return any type that implements the [`Pushable`] trait, and the value will
/// be returned on the Lua side by `require`.
///
/// # Examples
///
/// Let's say your crate only consists of this single `lib.rs` file:
///
/// ```ignore
/// // lib.rs
///
/// #[nvim_oxi::plugin]
/// fn my_plugin() -> u32 {
///     42
/// }
/// ```
///
/// Once the crate is compiled and the resulting dynamic library is placed
/// under `lua/my_plugin.{so|dylib|dll}` somewhere in Neovim's [`runtimepath`],
/// it can be loaded with:
///
/// ```lua
/// local ret = require("my_plugin")
/// assert(ret == 42)
/// ```
///
/// [`Pushable`]: https://docs.rs/nvim-oxi/latest/nvim_oxi/lua/trait.Pushable.html
/// [`runtimepath`]: https://neovim.io/doc/user/options.html#'runtimepath'
///
/// # Attributes
///
/// ## `nvim-oxi`
///
/// The code generated by this macro includes calls to functions defined in the
/// `nvim-oxi` crate, which is expected to be in scope under `::nvim_oxi`. This
/// can cause problems if you renamed the crate in your `Cargo.toml` or if it's
/// re-exported from another crate.
///
/// In these cases, you can use the `nvim_oxi` attribute to specify the path to
/// `nvim-oxi`.
///
/// For example, let's say your crate has a single dependency called `foo`
/// whose whose `lib.rs` re-exports `nvim-oxi` as `nvim`:
///
/// ```ignore
/// // foo's lib.rs
/// pub use nvim_oxi as nvim;
/// ```
///
/// Doing this would generate a compilation error because `nvim_oxi` is not in
/// scope:
///
/// ```compile_fail
/// #[foo::nvim::plugin]
/// fn my_plugin() {}
/// ```
///
/// To fix this, you can use the `nvim_oxi` attribute to specify the correct
/// path:
///
/// ```ignore
/// #[foo::nvim::plugin(nvim_oxi = foo::nvim)]
/// fn my_plugin() {}
/// ```
///
/// == NEW DOCS ========================================
///
/// A wrapper around [`mlua::lua_module`] that marks a function
/// as the entrypoint of the plugin.
///
/// [`mlua::lua_module`]: ::mlua::lua_module
///
/// The function wrapped by this macro will be called by Neovim when the user
/// loads the plugin as a Lua module with [`require`] (or with the lower level
/// [`package.loadlib`]).
///
/// The expected function signature is
/// `(lua: &mlua:Lua) -> mlua::Result<impl mlua::IntoLua>`
/// the inner value will be returned on the Lua side when the plugin is loaded.
///
/// The exported module's name can be changed with the `name` attribute option.
/// The `skip_memory_check` attribute option can be used to improve performance
/// at the risk of risk of having uncaught exceptions and memory leaks.
/// See the [`lua_module` documentation] for more details.
///
/// Unlike the original ['nvim-oxi::plugin'] macro, there is no `nvim-oxi`
/// attribute option, please ensure you have both `mlua` and `nvim-oximlua`
/// available in the namespace where you are using this macro.
///
/// [`require`]: https://www.lua.org/manual/5.1/manual.html#pdf-require
/// [`package.loadlib`]: https://www.lua.org/manual/5.1/manual.html#pdf-package.loadlib
/// [`lua_module` documentation]: ::mlua::lua_module
/// ['nvim-oxi::plugin']: https://docs.rs/nvim-oxi/latest/nvim_oxi/attr.plugin.html
///
/// # Examples
///
/// Let's say your crate only consists of this single `lib.rs` file:
///
/// ```ignore
/// // lib.rs
///
/// #[nvim_oximlua::plugin]
/// fn my_plugin() -> u32 {
///     42
/// }
/// ```
///
/// Once the crate is compiled and the resulting dynamic library is placed
/// under `lua/my_plugin.{so|dylib|dll}` somewhere in Neovim's [`runtimepath`],
/// it can be loaded with:
///
/// ```lua
/// local ret = require("my_plugin")
/// assert(ret == 42)
/// ```
///
/// [`Pushable`]: https://docs.rs/nvim-oxi/latest/nvim_oxi/lua/trait.Pushable.html
/// [`runtimepath`]: https://neovim.io/doc/user/options.html#'runtimepath'
///
/// # Attributes
///
/// ## `nvim-oxi`
///
/// The code generated by this macro includes calls to functions defined in the
/// `nvim-oxi` crate, which is expected to be in scope under `::nvim_oxi`. This
/// can cause problems if you renamed the crate in your `Cargo.toml` or if it's
/// re-exported from another crate.
///
/// In these cases, you can use the `nvim_oxi` attribute to specify the path to
/// `nvim-oxi`.
///
/// For example, let's say your crate has a single dependency called `foo`
/// whose whose `lib.rs` re-exports `nvim-oxi` as `nvim`:
///
/// ```ignore
/// // foo's lib.rs
/// pub use nvim_oxi as nvim;
/// ```
///
/// Doing this would generate a compilation error because `nvim_oxi` is not in
/// scope:
///
/// ```compile_fail
/// #[foo::nvim::plugin]
/// fn my_plugin() {}
/// ```
///
/// To fix this, you can use the `nvim_oxi` attribute to specify the correct
/// path:
///
/// ```ignore
/// #[foo::nvim::plugin(nvim_oxi = foo::nvim)]
/// fn my_plugin() {}
/// ```
pub use macros::plugin;
